models/Solicitudpermisos.php
<?php

namespace app\models;

use Yii;
use app\models\Tiposdetalles;
use app\models\Users;
use app\models\Incapacidades;

/**
 * This is the model class for table "solicitudpermisos".
 *
 * @property int $idsolicitudpermisos
 * @property int $usuarioIdusuario
 * @property int $motivoId
 * @property string $fechaInicio
 * @property string $fechaFin
 * @property string $fechaCreacion
 * @property string $tiempoRepuesto
 * @property string $estado
 * @property int $anulado
 * @property string $observaciones
 * * @property string $incapacidadesIdincapacidad
 *
 * @property TiposDetalles $motivo
 * @property Incapacidades $ruta
 * @property Users $usuarioIdusuario0
 */
class Solicitudpermisos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'solicitudpermisos';
    }

    /**
     * {@inheritdoc
     */
    public function rules()
    {
        return [
            [['fechaCreacion','motivoId'], 'required'],
            [['idsolicitudpermisos', 'usuarioIdusuario','estadoId','usuarioAutoriza'], 'integer'],
            [['fechaInicio', 'fechaFin','horaInicio','horaFin', 'fechaCreacion', 'motivoId','diacompleto'], 'safe'],
            [['tiempoRepuesto'], 'string', 'max' => 200],
            [['observaciones','observacionJefeInmediato'], 'string', 'max' => 1000],
            [['idsolicitudpermisos'], 'unique'],
            [['usuarioIdusuario'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['usuarioIdusuario' => 'id']],
            [['usuarioAutoriza'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['usuarioAutoriza' => 'id']],
            [['incapacidad'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],            
        ];
    }
    public function upload()
    {
        if($this->validate()){
            $this->incapacidad->saveAs('images/' .$this->incapacidad->baseName.'.'.$this->incapacidad->extension);
            return true;            
        }else{
            return false;
        }
    }
    public function validacion()
    {
        if($this->incapacidad->extensions != ('png, jpg, pdf'))
        {
            echo "Archivos no validos";
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'idsolicitudpermisos' => 'Idsolicitudpermisos',
            'usuarioIdusuario' => 'Usuario Idusuario',
            'motivoId' => 'Motivo',
            'fechaInicio' => 'Fecha inicio',
            'fechaFin' => 'Fecha Fin',
            'fechaCreacion' => 'fecha creacion',
            'tiempoRepuesto' => 'tiempo repuesto',
            'estadoId' => 'Estado',
            'observaciones' => 'Observacion',
            'usuarioAutoriza'=> 'Jefe inmediato',
            'observacionJefeInmediato'=> 'observacion',
            'incapacidadesIdincapacidad' => 'idincapacidad',
            'horaInicio'=> 'Hora inicio',
            'horaFin'=> 'Hora fin',
            'diacompleto'=>'Dia completo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTiposdetalles()
    {
        return $this->hasOne(tiposdetalles::className(), ['idTipoDetalle' => 'motivoId']);
    }

    public function getEstado()
    {
       return $this->hasOne(tiposdetalles::className(), ['idTipoDetalle' => 'estadoId']); 
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasOne(users::className(), ['id' => 'usuarioIdusuario']);
    }

    public function getJefeinmediato()
    {
        return $this->hasOne(users::className(), ['id'=>'usuarioAutoriza']);
    }

    public function getRevisanomina()
    {
       return $this->hasOne(tiposdetalles::className(), ['idTipoDetalle' => 'apruebanomina']);
    }

    public function getIncapacidades()
    {
        return $this->hasOne(incapacidades::className(), ['solicitudpermisosIdsolicitudpermisos'=>'idsolicitudpermisos']);
    }

}

models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $authKey
 * @property string $accessToken
 * @property integer $activate
 * @property integer $role
 * @property string $nombres
 * @property string $apellidos
 * @property string $foto
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombres', 'apellidos', 'numeroIdentificacion', 'direccion' ,'telefono' ,'username', 'email','role', 'password'], 'required'],
            [['activate','numeroIdentificacion'], 'integer'],
            [['foto','role'], 'string'],
            [['username'], 'string', 'max' => 50],
            [['email'], 'string', 'max' => 80],
            [['email'], 'email'],
            [['password', 'authKey', 'accessToken'], 'string', 'max' => 250],
            [['direccion'], 'string', 'max' => 150],
            ['password', 'match', 'pattern' => "/^.{8,16}$/", 'message' => 'Mínimo 6 y máximo 16 caracteres'],
            [['nombres', 'apellidos'], 'string', 'max' => 60],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
            'authKey' => 'Auth Key',
            'accessToken' => 'Access Token',
            'activate' => 'Activate',
            'role' => 'Role',
            'nombres' => 'Nombres',
            'apellidos' => 'Apellidos',
            'foto' => 'Foto',
        ];
    }

    public function getRol()
    {
        return $this->hasOne(Rol::className(), ['id' => 'role']);
    }

      public function email_existe($attribute, $params)
      {
    
    //Buscar el email en la tabla
    $table = Users::find()->where("email=:email", [":email" => $this->email]);
    
    //Si el email existe mostrar el error
    if ($table->count() == 1)
    {
      $this->addError($attribute, "El email seleccionado existe");
    }
      }
    public function getCargo()
    {
        return $this->hasOne(Cargos::className(), ['idCargo' => 'cargos_idcargos']);
    }

    public function getPuntorecaudo()
    {
        return $this->hasOne(Puntosrecaudo::className(), ['idPuntoRecaudo' => 'puntosrecaudo_idpuntosrecaudo']);
    }
    
      public function username_existe($attribute, $params)
      {
    //Buscar el username en la tabla
    $table = Users::find()->where("username=:username", [":username" => $this->username]);
    
    //Si el username existe mostrar el error
    if ($table->count() == 1)
    {
                  $this->addError($attribute, "El usuario seleccionado existe");
    }
      }
    
}

controllers/SolicitudpermisosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Solicitudpermisos;
use app\models\Revisanominasearch;
use app\models\Aprobadasnominasearch;
use app\models\solicitudpermisosSearch;
use app\models\PendientesSearch;
use app\models\AprobadasSearch;
use app\models\RechazadasSearch;
use app\models\Users;
use app\models\Cargos;
use app\models\Tiposdetalles;
use app\models\Puntosrecaudo;
use yii\web\UploadedFile;
use yii\web\Controller;
use yii\web\time;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\db\Query;





/**
 * SolicitudpermisosController implements the CRUD actions for solicitudpermisos model
 */
class SolicitudpermisosController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all solicitudpermisos models.
     * @return mixed
     */
    public function actionIndex()

    {        
        $searchModel = new solicitudpermisosSearch();
        $model = Solicitudpermisos::find()->where(['usuarioIdusuario'=>(Yii::$app->user->identity->id)])->all();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $usuarios = Solicitudpermisos::find()->where(['usuarioIdusuario'=>(Yii::$app->user->identity->id)])->all();
        $jefeinmediato = Solicitudpermisos::find()->where(['usuarioAutoriza'=>(Yii::$app->user->identity->id)] && ['estadoId'=>(123)])->all(); 
        $validaU = Users::find()->where(['id'=>(Yii::$app->user->identity->id)])->all();                                   
        $pendientes1=false;
        $usuarios1=false; 
        $jefeinmediato1=false;    
        $jefeinmediato2=false;
        $valusu=false; 
              
        // echo $sinSolcitudes; die ();
        //      echo '<pre>';
        //    print_r($validaU);
        //   die();
        foreach ($validaU as $value) 
        {
            if($value->id==(Yii::$app->user->identity->id) && $value->jefe_inmediato!=1){
                $valusu=true;
            }
        }

        foreach ($model as $pendientes) {            
               if ($pendientes->usuarioIdusuario ==(Yii::$app->user->identity->id) && $pendientes->estadoId ==122 || $pendientes->apruebanomina==136){
                $pendientes1=true;
            }                                   
        }
     
        foreach ($usuarios as $usuario) {        
            if ($usuario->usuarioIdusuario ==(Yii::$app->user->identity->id)){
            $usuarios1=true;
            }                                   
        }

        foreach ($jefeinmediato as $jefe) {        
            if ($jefe->usuarioAutoriza ==(Yii::$app->user->identity->id)){
            $jefeinmediato1=true;
            }                                   
        }

        foreach ($jefeinmediato as $jefe) {        
            if ((Yii::$app->user->identity->id==2)&& $jefe->estadoId ==123){
            $jefeinmediato2=true;
            }                                   
        }     
     
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'pendientes1' => $pendientes1, 
            'usuarios1' => $usuarios1, 
            'jefeinmediato1' => $jefeinmediato1, 
            'model'=> $model,
            'valusu'=>$valusu,

        ]);
    
    }
    public function actionReport()
    {  
        return $this->render('reporte');                       
    
    }
    /**
     * Displays a single solicitudpermisos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        // $model= Solicitudpermisos::find()->where(['usuarioAutoriza=>'=>(Yii::$app->user->identity->id)])->all();
        // $gestionar=false;


        //   foreach ($model as $gestionar) {

        //     if ($gestionar->usuarioAutoriza==(Yii::$app->user->identity->id) && $pendientes->estadoId ==4){

        //         $gestionar=true;
        //     }
        //     # code...
        // }
        

        
        return $this->render('view', [
            'model' => $this->findModel($id),            
        ]);

        return $this->render('revisanomina', [
            'model' => $this->findModel($id),            
        ]);
    }

    /**
     * Creates a new solicitudpermisos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()

    
    {
            $model = new Solicitudpermisos();

            if ($model->load(Yii::$app->request->post()) ) {

                // echo "<pre>";
                // print_r($_REQUEST);die;

                $model->fechaInicio = $_REQUEST['fechaInicio'];
                $model->fechaFin = $_REQUEST['fechaFin'];
                $model->horaInicio=$_REQUEST['horaInicio'];
                $model->horaFin=$_REQUEST['horaFin'];
                $model->incapacidad=UploadedFile::getInstance($model,'incapacidad');
                // echo "<pre>";
                // print_r($model->incapacidad);die;


                if($model->save()){   
                    if ($model->incapacidad) {
                        if ($model->upload()) {
                            // file is uploaded successfully
                        }else{
                            echo 'no guardo';
                            die();
                        }
                    }               
                    // $model->incapacidad->saveAs('intranetosa/images/' .$model->incapacidad->name.'.'.$model->incapacidad->extension);
                    return $this->redirect(['view', 'id' => $model->idsolicitudpermisos]);

                }else{
                    echo '<pre>';
                    print_r( $model->getErrors() );
                    die();
                }
            }

            //$users=users::model()->findByPk($id);
            $users = users::findOne(Yii::$app->user->identity->id);
            $cargos = cargos::findOne(1);
            $puntosrecaudo= puntosrecaudo::findOne(1);
            $tiposdetalles= tiposdetalles::findOne(1);
            // echo "<pre>";
            // print_r($cargos); die;
            //$usuar = users::find()->where(['id' => $id])->all();

            return $this->render('create', [
                'model' => $model,
                'users'=>$users,
                'cargos'=>$cargos,
                'puntosrecaudo'=>$puntosrecaudo,
                'tiposdetalles'=>$tiposdetalles,




            ]);
            
          
    }

    /**
     * Updates an existing solicitudpermisos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post()) ) { 
                $model->fechaInicio = $_REQUEST['fechaInicio'];
                $model->fechaFin = $_REQUEST['fechaFin'];
                $model->horaInicio=$_REQUEST['horaInicio'];
                $model->horaFin=$_REQUEST['horaFin'];
                $model->save();
        //  echo '<pre>'       ;
        //  print_r ($model);
        //  die();

        if    ($model->incapacidad=UploadedFile::getInstance($model,'incapacidad')){
            
            if($model->save()){                   
                        if ($model->incapacidad) {                        
                            if ($model->upload()) {
                                // file is uploaded successfully
                            }else{
                                echo 'no guardo';
                                die();
                            }
                        }               
                        // $model->incapacidad->saveAs('intranetosa/images/' .$model->incapacidad->name.'.'.$model->incapacidad->extension);
                        // return $this->redirect(['view', 'id' => $model->idsolicitudpermisos]);
    
                    }else{
                        echo '<pre>';
                        print_r( $model->getErrors() );
                        die();
                    }
        }           

            return $this->redirect(['view', 'id' => $model->idsolicitudpermisos]);            
    }
         
        $users = users::findOne(Yii::$app->user->identity->id);

        return $this->render('update', [
            'model' => $model,
            'users'=> $users,
        ]);
    }

    /**
     * Deletes an existing solicitudpermisos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        // $this->findModel($id)->delete();

        // return $this->redirect(['index']);
        
    }

    /**
     * Finds the solicitudpermisos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return solicitudpermisos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = solicitudpermisos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    public function actionEliminardoc($id)
    {


        // echo '<pre>';
        //     print_r($id.'no trae nada');
        //     die();
        $query = new Query();
        $connection = Yii::$app->db;

views/solicitudpermisos/_form.php
<div class="container-fluid">
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Users;
use kartik\date\DatePicker;
use yii\db\Connection;
use app\models\Cargos;
use app\models\Puntosrecaudo;
use app\models\Tiposdetalles;
use yii\widgets\DetailView;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\solicitudpermisos */
/* @var $form yii\widgets\ActiveForm */
?>
<script src="<?php echo Url::base(); ?>/js/jquery-1.11.3.min.js"></script>
<div class="solicitudpermisos-form">
       <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data'],'id'=>'form']); ?>            
       <?php echo $form->field($model, 'usuarioIdusuario')->hiddenInput(['value'=> (Yii::$app->user->identity->id)])->label(false); ?>
  <!-- //////////////////////////////////////PANEL DATOS EMPLEADO////////////////////////////////////////////////////// -->    
       <div class="card border-primary mb-3">
            <div class="card-header text-white" style="background-color: #337AB7;">Datos de usuario</div>
                <div class="card-body">                                         
                    <div class="col-lg-12">  
                        <div class="table-responsive">                                                   
                            <table class="table">                                
                                     <thead><tr>                                            
                                            <th scope="col">Nombres</th>
                                            <th scope="col">Apellidos</th>
                                            <th scope="col">Documento</th>                                            
                                            </tr></thead>   
                                    <tbody><tr>
                                            <td> <?php echo $users->nombres; ?></td>                                                                                                        
                                            <td> <?php echo $users->apellidos; ?></td>                                                                                        
                                            <td> <?php echo $users->numeroIdentificacion; ?></td>                                                                                   
                                           </tr></tbody>                                                                                                                                                         
                                    <thead><tr>                                            
                                            <th scope="col">Telefono</th>
                                            <th scope="col">Cargo</th>
                                            <th scope="col">Regional</th>                                            
                                            </tr></thead>   
                                    <tbody><tr>
                                          <td> <?php echo $users->telefono; ?></td>                                                                                        
                                          <td> <?php echo $users->cargo->nombre; ?></td>                                                                                          
                                          <td> <?php echo  $users->puntorecaudo->nombre; ?></td>                                                                                            
                                          </tr></tbody>                                         
                              </table> 
                           </div>   
                    </div>                                                                         
                </div>
        </div>          
<!-- //////////////////////////////////////PANEL DATOS DE SOLICITUD////////////////////////////////////////////////////// -->
        <div class="card border-primary mb-3">
            <div class="card-header text-white" style="background-color: #337AB7;">Datos de solicitud</div>
                  <div class="card-body">                                                                                                                               
                        <div class="col-lg-12" > 
                         <div class="table-responsive"> 
                            <table class="table">                                                                  
                                  <tbody><tr>
                                  <td>
                                    <?= $form->field($model, 'motivoId')->dropDownList(ArrayHelper::map(tiposdetalles::find()
                                                              ->where(['tipo_idtipo' => 15 ])
                                                              ->orderBy(['nombre'=>SORT_ASC])->all(), 'idTipoDetalle', 'nombre'), 
                                                       [
                                                      'class'=>'form-control a',
                                                      'prompt'=>'[-- Seleccione motivo--]',  
                                                      'required'=>'required',                                                    
                                                       ]                                                      
                                                  ) ?>
                                          <div class="help-block"></div>                                                                                                    
                                   </td>
                                   <td>
                                        <?= $form->field($model, 'usuarioAutoriza')->dropDownList(ArrayHelper::map(users::find()
                                                              ->where(['jefe_inmediato'=>[1]])
                                                              ->orderBy(['nombres'=>SORT_ASC])->all(), 'id',function ($model, $defaultValue){
                                                                return $model->nombres .' '. $model->apellidos;
                                                              }), 
                                                      [
                                                      'required'=>'required',
                                                      'class'=>'form-control a',
                                                      'prompt'=>'[-- Seleccione usuario--]',                                                    
                                                      ]
                                          ) ?>
                                    </td>
                                    <td>
                                    <?php
                                       echo $form->field($model, 'diacompleto')->dropDownList(['1' => 'Si', '0' => 'No'],['required'=>'required','class'=>'form-control a','prompt'=>'[-- Seleccione--]','id'=>'diacompleto' ]);
                                       ?>                                                                                                
                                   </td>
                                   <td><input type="button" class="btn btn-primary" value="Agregar horas" class="form-control"></td>      
                                   </tbody></tr>  
                                
                                  <tbody><tr>
                                      <td>       
                                        <label for="start">Fecha Inicio</label>             
                                        <input type="date" class="form-control" id="start" value="<?php echo $model->fechaInicio ?>" name="fechaInicio" id="finicio" required="required">
                                     </td> 
                                     <td>                                            
                                       <label for="start">Fecha Fin</label>                                                   
                                       <input type="date" class="form-control" id="start" value="<?php echo $model->fechaFin ?>" name="fechaFin" id="ffin" required="required">                                            
                                     </td>                                        
                                       <td> <?= $form->field($model, 'tiempoRepuesto')->textInput() ?></td>                                                                             
<!--//////////////////////////////////////CARGAR ARCHIVO//////////////////////////////////////-->                                       
                                       <td id="incapacidad" class="d-none">                                         
                                         <?= $form->field($model, "incapacidad")->fileInput(['multiple' => false, 'class'=> 'a'])->label('Adjuntar incapacidad') ?>                                         
                                       </td>                                       
                                       <?php echo $form->field($model, 'fechaCreacion')->hiddenInput(['value'=> date('Y-m-d')])->label(false); ?>
                                       <td><?php echo $form->field($model, 'estadoId')->hiddenInput(['value'=>122 ])->label(false); ?></td>                                        
                                  </tr></tbody>                                                                                                                                                                                         
                                  <tbody><tr id="hora" class="d-none">
                                       <td>
                                          <label for="start">Hora inicio</label>  
                                          <input type="time" class="form-control" name="horaInicio" value="00:00">
                                       </td> 
                                       <td>
                                          <label for="start">Hora fin</label>  
                                          <input type="time" class="form-control" name="horaFin" value="00:00">
                                       </td> 
                                  </tr></tbody>
                                </div></div></div> 
                          </table>        
                       </div>   
                                <div class="col-lg-12" >
                                <div class="table-responsive"> 
                                <table class="table">                                 
                                  <tbody><tr>                                                                                                                                                                                                                                                                             
                                        <div class="help-block"></div>  
                                        <td><?= $form->field($model, 'observaciones')->textarea(['maxlength' => true,'style'=>'height: 100px'])?></td>                                                                                                                                                                  
                                   </tr></tbody>
                                  </div>                                     
                                </table>
                                </div>
                       </div>           
                                </div>                                                                                                                           
                    </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        </div>                    
                <div class="form-group">
                    <?= Html::submitButton('Guardar', ['class' => 'btn btn-success','id'=>'guardar']) ?>
                </div>

                <?php ActiveForm::end(); ?>
</div>

<script type="text/javascript">
        $(document).ready(function(){
                // alert("fff");
                $('#solicitudpermisos-motivoid').on('change',function(){           
                        if($(this).val()==127){            
                                $('#incapacidad').removeClass('d-none');      
                        }else{
                                $("#incapacidad").addClass('d-none');
                        }        
                });                  
                $(".btn").click(function(){
                        $('#hora').removeClass('d-none');
                         $("#hora").collapse('toggle');                                       
                });
                $('#diacompleto').on('change',function(){           
                        if($(this).val()==0){            
                                $('#hora').removeClass('d-none');      
                        }else{
                                $("#hora").addClass('d-none');
                        }        
                });                                                                                        
        }); // document ready                   
</script>