models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $authKey
 * @property string $accessToken
 * @property integer $activate
 * @property integer $role
 * @property string $nombres
 * @property string $apellidos
 * @property string $foto
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombres', 'apellidos', 'numeroIdentificacion', 'direccion' ,'telefono' ,'username', 'email','role', 'password'], 'required'],
            [['activate','numeroIdentificacion'], 'integer'],
            [['foto','role'], 'string'],
            [['username'], 'string', 'max' => 50],
            [['email'], 'string', 'max' => 80],
            [['email'], 'email'],
            [['password', 'authKey', 'accessToken'], 'string', 'max' => 250],
            [['direccion'], 'string', 'max' => 150],
            ['password', 'match', 'pattern' => "/^.{8,16}$/", 'message' => 'Mínimo 6 y máximo 16 caracteres'],
            [['nombres', 'apellidos'], 'string', 'max' => 60],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
            'authKey' => 'Auth Key',
            'accessToken' => 'Access Token',
            'activate' => 'Activate',
            'role' => 'Role',
            'nombres' => 'Nombres',
            'apellidos' => 'Apellidos',
            'foto' => 'Foto',
        ];
    }

    public function getRol()
    {
        return $this->hasOne(Rol::className(), ['id' => 'role']);
    }

      public function email_existe($attribute, $params)
      {
    
    //Buscar el email en la tabla
    $table = Users::find()->where("email=:email", [":email" => $this->email]);
    
    //Si el email existe mostrar el error
    if ($table->count() == 1)
    {
      $this->addError($attribute, "El email seleccionado existe");
    }
      }
    public function getCargo()
    {
        return $this->hasOne(Cargos::className(), ['idCargo' => 'cargos_idcargos']);
    }

    public function getPuntorecaudo()
    {
        return $this->hasOne(Puntosrecaudo::className(), ['idPuntoRecaudo' => 'puntosrecaudo_idpuntosrecaudo']);
    }
    
      public function username_existe($attribute, $params)
      {
    //Buscar el username en la tabla
    $table = Users::find()->where("username=:username", [":username" => $this->username]);
    
    //Si el username existe mostrar el error
    if ($table->count() == 1)
    {
                  $this->addError($attribute, "El usuario seleccionado existe");
    }
      }
    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\Response;
use app\models\FormRegister; 
use app\models\Users; 
use app\models\AccesosDirectos; 
use yii\widgets\ActiveForm;
use app\models\User;
use app\models\Rol;


// Yii::import('application.vendors.*');
// require(__DIR__ . '/../vendor/phpmailer2/PHPMailerAutoload.php');
// require(__DIR__ . '/../vendor/phpmailer2/class.phpmailer.php');

Yii::$classMap['phpmailer2'] = __DIR__ . '/../vendor/phpmailer2/PHPMailerAutoload.php';
use phpmailer2;

class SiteController extends Controller
{
   public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        //'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    // 'logout' => [''],
                ],
            ],
        ];

    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {

        $userIdentity = Users::findOne(yii::$app->user->identity->id);
        $accesosDirectos = AccesosDirectos::find()
                            ->where(['IN','idRol', explode(',', yii::$app->user->identity->role)])
                            ->andWhere(['estado'=>1])
                            ->all();
        $roles = Rol::find()->all();

        return $this->render('index',[
            'userIdentity' => $userIdentity,
            'accesosDirectos' => $accesosDirectos,
            'roles' => $roles
        ]);
        return $this->render('cartelera-virtual/index');
    }

    public function actionIndexweb()
    {
        return $this->redirect(["cartelera-virtual/index"]);
    }

     public function actionLogin()
     {
         if (!\Yii::$app->user->isGuest) {
             return $this->redirect(["site/index"]);
         }

        $model = new LoginForm();
         if ($model->load(Yii::$app->request->post()) && $model->login()) {

             return $this->redirect(["site/index"]);

         } else {
             return $this->render('login', [
                 'model' => $model,
             ]);
        }
     }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionUser(){
        return $this->render("user");
    }

    public function actionAdmin(){
        return $this->render("admin");
    }

 

    private function randKey($str='', $long=0){
        $key = null;
        $str = str_split($str);
        $start = 0;
        $limit = count($str)-1;

        for($x=0; $x<$long; $x++)
        {
            $key .= $str[rand($start, $limit)];
        }

        return $key;
    }

       

     public function actionConfirm(){

        $table = new Users;

        if (Yii::$app->request->get())
        {
            //Obtenemos el valor de los parámetros get
            $id = Html::encode($_GET["id"]);
            $authKey = $_GET["authKey"];
        
            if ((int) $id)
            {
                //Realizamos la consulta para obtener el registro
                $model = $table
                ->find()
                ->where("id=:id", [":id" => $id])
                ->andWhere("authKey=:authKey", [":authKey" => $authKey]);
      
                //Si el registro existe
                if ($model->count() == 1)
                {
                    $activar = Users::findOne($id);
                    $activar->activate = 1;

                    if ($activar->update())
                    {
                        echo "Enhorabuena registro llevado a cabo correctamente, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";
                    }
                    else
                    {
                        echo "Ha ocurrido un error al realizar el registro, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";

                    }
                }
                else //Si no existe redireccionamos a login
                {
                    return $this->redirect(["site/login"]);
                }
            }
            else //Si id no es un número entero redireccionamos a login
            {
                return $this->redirect(["site/login"]);
            }
        }
    }

      
    public function actionRegister()
    { 
        //Creamos la instancia con el model de validación
        $model = new FormRegister;

        //Mostrará un mensaje en la vista cuando el usuario se haya registrado
        $msg = null;

        //Validación mediante ajax
        if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax)
        {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);

        }

        if ($model->load(Yii::$app->request->post()))
        {

            if($model->validate())
            {

                //Preparamos la consulta para guardar el usuario
                $user = new Users;
                $user->username = $model->username;
                $user->email = $model->email;
                $user->role = $model->role; 
                $user->nombres = $model->nombres; 
                $user->apellidos = $model->apellidos; 
                $user->numeroIdentificacion = $model->numeroIdentificacion; 
                $user->direccion = $model->direccion; 
                $user->telefono = $model->telefono; 
                // $user->grupo_idgrupo = $model->grupo_idgrupo; 

                //Encriptamos el password
                $user->password = crypt($model->password, Yii::$app->params["salt"]);
                // $user->password = md5($model->password);

                //Creamos una cookie para autenticar al usuario cuando decida recordar la sesión, esta misma
                //clave será utilizada para activar el usuario
                $user->authKey = $this->randKey("abcdef0123456789", 200);
                //Creamos un token de acceso único para el usuario
                $user->accessToken = $this->randKey("abcdef0123456789", 200);
                //Si el registro es guardado correctamente
                if ($user->insert())
                {
                    $newUser = Users::findOne($user->id);
                    $msg = "El funcionario ".$newUser->username.' ha sido registrado';
                    $alert = 'success';
                    $graphicon = 'ok';
                    return $this->render("newUser", 
                        [
                            "model" => $newUser, 
                            "msg" => $msg,
                            "alert" => $alert,
                            "graphicon" => $graphicon
                        ]
                    );
                }
                else
                {
                    $newUser = false;
                    $msg = "Ha ocurrido un error al llevar a cabo tu registro";
                    $alert = 'danger';
                    $graphicon = 'remove';

                    return $this->render("newUser", 
                        [
                            "model" => $newUser, 
                            "msg" => $msg,
                            "alert" => $alert,
                            "graphicon" => $graphicon
                        ]
                    );
                }
            }
            else
            {
                $model->getErrors();

            }
        }
        $roles = Rol::find()->all();
        return $this->render("register", ["model" => $model, "msg" => $msg,"roles"=>$roles]);
    }


}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/admin.php
<h1>vista administrador</h1>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
?>
<div class="col-lg-12">

    <div class="jumbotron">
        <img width="250" src="<?php echo Url::base(); ?>/images/f52610_b3fa64f9ff4d4ac0a9d8f745fa6b0a82.png" alt="..." class="">
    </div>

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>


    <p>
        Por favor contactese con el area de Tecnologia. Gracias
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'OsaIn';
?>
<div class="site-index">
    <?php $rolesPerfil = ''; ?>
    <?php $init = true; ?>
    <?php $idRolesPerfil = explode(',', $userIdentity->role); ?>
    <?php foreach ($roles as $r) { ?>
      <?php if (in_array($r->id, $idRolesPerfil)) { ?>
        <?php if ($init) { ?>
          <?php $rolesPerfil = $r->nombre; ?>
          <?php $init = false; ?>
        <?php }else{ ?>
          <?php $rolesPerfil = $rolesPerfil . '/' . $r->nombre; ?>
        <?php } ?>
      <?php } ?>
    <?php } ?>
    <div class="jumbotron">
        <h1><?php echo yii::$app->name ?> 1.0</h1>

        <p class="lead"><strong><?php echo $rolesPerfil; ?></strong></p>
        <img width="150" src="<?php echo Url::base(); ?>/images/fotos/<?php echo yii::$app->user->identity->foto; ?>" alt="..." class="img-circle">
        <p class="lead"><?php echo yii::$app->user->identity->nombres.' '.yii::$app->user->identity->apellidos; ?></p>
    </div>

    <div class="body-content">
        <div class="col-lg-12">
            <div class="col-lg-8 noPadding form-group col-lg-offset-2">
                <?php $accesosArray = array(); ?>
                <?php foreach ($accesosDirectos as $ac) { ?>
                    <?php if (!in_array($ac->etiqueta,$accesosArray)) { ?>
                        <div class="col-lg-4 form-group">
                            <?= Html::a( $ac->etiqueta, [$ac->action, 'id' => 12], ['class' => 'btn btn-'.$ac->color.' btn-block btn-lg']) ?>
                            <?php array_push($accesosArray, $ac->etiqueta); ?>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

views/site/indexWeb.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'OsaIn';
?>
<div class="site-index">
    


    
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>

<?php $form = ActiveForm::begin([
    'id' => 'login-form',
]); ?>

    <div class="col-lg-12 form-login">
        <div class="col-lg-4 col-lg-offset-4 content-login">
                <div class="col-lg-12" style="height:15px"></div>
            <div class="col-lg-10 col-lg-offset-1">
                <center><h1>OsaIn</h1></center>
                <div class="col-lg-12 noPadding">
                    <div class="form-group has-feedback">
                        <?= $form->field($model, 'username')->textInput(['placeholder' => 'Usuario', 'class' => 'form-control'])->label(false) ?>
                        <i class="glyphicon glyphicon-user form-control-feedback-left form-control-feedback"></i>
                    </div>
                </div>
                <div class="col-lg-12 noPadding">
                    <div class="form-group has-feedback">
                        <i class="icon-key"></i>
                        <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Contraseña', 'class' => 'form-control'])->label(false) ?>
                    </div>
                </div>
                <div class="col-lg-12 noPadding">
                    <?= $form->field($model, 'rememberMe')->checkbox()->label('Keep me logged on this computer') ?>
                </div>
                <div class="form-group col-lg-12 noPadding">
                        <br>
                        <div class="col-lg-12 noPadding ol-lg-offset-2">
                            <?= Html::submitButton('Login', ['class' => 'btn btn-default btn-block text-bold', 'name' => 'login-button']) ?>
                        </div>
                </div>
                <div class="col-lg-12" style="height:30px"></div>
            </div>
        </div>
    </div>
<?php ActiveForm::end(); ?>

views/site/newUser.php
<?php 
	use yii\helpers\Html;
	use yii\widgets\DetailView;
	use yii\helpers\Url;
?>

<div class="alert alert-<?php echo $alert ?>" role="alert">
  <span class="glyphicon glyphicon-<?php echo $graphicon;  ?>" aria-hidden="true"></span>
  <?php echo $msg; ?>
</div>
<?php if ($model) { ?>
	<div class="users-view">

	    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
	    <div class="jumbotron">
	        <img width="150" src="<?php echo Url::base(); ?>/images/fotos/<?php echo $model->foto; ?>" alt="..." class="img-circle">
	        <p class="lead"><?php echo $model->nombres.' '.$model->apellidos; ?></p>
	    </div>

	    <!-- informacion personal -->
	    <div class="panel panel-primary">
	        <div class="panel-heading">Informacion personal</div>
	        <div class="panel-body">
	            <table class="table table-striped">
	                <tbody>
	                  <tr>
	                    <td><strong>Nombres: </strong><?php echo $model->nombres; ?></td>
	                    <td><strong>Apellidos: </strong><?php echo $model->apellidos; ?></td>
	                  </tr>
	                  <tr>
	                    <td><strong>Tipo de estado: </strong><?php echo $model->numeroIdentificacion; ?></td>
	                  </tr>
	                  <tr>
	                    <td><strong>Direccion: </strong><?php echo $model->direccion; ?></td>
	                    <td><strong>Telefono: </strong><?php echo $model->telefono; ?></td>
	                  </tr>
	                  <tr>
	                    <td colspan="2"><strong>Email: </strong><?php echo $model->email; ?></td>
	                  </tr>
	                </tbody>
	              </table>
	        </div>
	    </div>

	    <!-- informacion laboral -->
	    <div class="panel panel-primary">
	        <div class="panel-heading">Informacion laboral</div>
	        <div class="panel-body">
	            <table class="table table-striped">
	                <tbody>
	                  <tr>
	                    <td><strong>Username: </strong><?php echo $model->username; ?></td>
	                    <td><strong>Rol usuario: </strong><?php echo $model->rol->nombre; ?></td>
	                  </tr>
	                </tbody>
	              </table>
	        </div>
	    </div>
	    <p>
	        <?= Html::a('Actualizar informacion', ['funcionarios/update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
	        <?= Html::a('Registrar funcionario', ['site/register'], ['class' => 'btn btn-primary']) ?>
	        <?= Html::a('Volver', ['site/index'], ['class' => 'btn btn-primary']) ?>
	    </p> 
	</div>

<?php }else{ ?>
	<p>
	    <?= Html::a('Registrar funcionario', ['site/register'], ['class' => 'btn btn-primary']) ?>
	    <?= Html::a('Volver', ['site/index'], ['class' => 'btn btn-primary']) ?>
	</p> 
<?php } ?>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Cargos;
use app\models\Rol;
use kartik\date\DatePicker;
use yii\helpers\Url;
?>
  <script src="<?php echo Url::base(); ?>/js/jquery-1.11.3.min.js"></script>
<?php $form = ActiveForm::begin([
    'method' => 'post',
 'id' => 'formulario',
 'enableClientValidation' => false,
 'enableAjaxValidation' => true,
]);
?>

<div class="jumbotron">
    <img width="250" src="<?php echo Url::base(); ?>/images/f52610_b3fa64f9ff4d4ac0a9d8f745fa6b0a82.png" alt="..." class="">
    <!-- <p class="lead">Registro Usuarios OsaNet</p> -->
</div>
<center><h2>Registro usuarios OsaNet</h2></center>
<!-- ====== INFORMACION DE LA APLICACION ============ -->
<div class="panel panel-primary">
    <div class="panel-heading">Informacion de la aplicacion</div>
    <div class="panel-body">
        <div class="col-lg-12 noPadding">
            <div class="form-group col-lg-6">
             <?= $form->field($model, "username")->input("text") ?>   
            </div>
            <div class="form-group col-lg-6">
             <?= $form->field($model, "email")->input("email") ?>   
            </div>
        </div>
        <div class="col-lg-12 noPadding">
            <div class="form-group col-lg-6">
             <?= $form->field($model, "password")->input("password") ?>   
            </div>

            <div class="form-group col-lg-6">
             <?= $form->field($model, "password_repeat")->input("password") ?>   
            </div>
        </div>
    </div>
</div>
<!-- ====== INFORMACION PERSONAL ============ -->
<div class="panel panel-primary">
    <div class="panel-heading">Informacion personal</div>
    <div class="panel-body">
       <div class="col-lg-12 noPadding">
           <div class="form-group col-lg-6">
            <?= $form->field($model, "nombres") ?>   
           </div>

           <div class="form-group col-lg-6">
            <?= $form->field($model, "apellidos") ?>   
           </div>
       </div>
       <div class="col-lg-12 noPadding">
           <div class="form-group col-lg-6">
                <?= $form->field($model, "numeroIdentificacion") ?>   
           </div>
       </div> 
       <div class="col-lg-12 noPadding">
            <div class="form-group col-lg-6">
             <?= $form->field($model, "telefono") ?>   
            </div>
           <div class="form-group col-lg-6">
            <?= $form->field($model, "direccion") ?>   
           </div>
       </div>
    </div>
</div>

<!-- ============== ROLES ASOCIADOS AL PERFIL ============ -->
<div class="panel panel-primary">
  <div class="panel-heading">Roles Asociados al perfil</div>
  <div class="panel-body">
    <div class="col-lg-12 noPadding">
        <?php foreach ($roles as $r) { ?>
          <button type="button" class="btn btn-primary addRole" id="<?php echo $r->id; ?>">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <?php echo $r->nombre; ?>
          </button>
        <?php } ?>
        <?= $form->field($model, "role")->textInput(['readonly'=>'readonly']) ?>   
    </div>
  </div>
</div>

<?= Html::submitButton("Registrar usuario", ["class" => "btn btn-primary"]) ?>

<?php $form->end() ?>

<!-- ================ JS =========== -->
<script>
  $(document).ready(function(){
    $(".addRole").click(function(){
      if ($(this).hasClass('select')) {
        $(this).removeClass('select');
        $(this).addClass('btn-primary');
        $(this).removeClass('btn-success');
      }else{
        $(this).addClass('btn-success');
        $(this).addClass('select')
        $(this).removeClass('btn-primary');
      }
      validateRoleActive();
    });
  })
  // =============== FUNCIONES ==================
  function validateRoleActive(){
    var concatRole = '';
    var init = false;
    $(".addRole").each(function(){
      console.log($(this).attr('class'));
      if ($(this).hasClass('select')) {
        if (init) {
          concatRole = concatRole + ',' + $(this).attr('id');
        }else{
          concatRole = $(this).attr('id');
          init = true;
        }
      }
    });
    $("#formregister-role").val(concatRole);
  }
</script>

views/site/user.php
<h1>vista user normal</h1>
<?php echo 'asdfasdf'; ?>