models/Documentos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "documentos".
 *
 * @property integer $documento_id
 * @property string $documento_nombre
 * @property integer $documento_proceso_id
 * @property integer $documento_carpeta_id
 */
class Documentos extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'documentos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['documento_proceso_id', 'documento_carpeta_id'], 'integer'],
            [['documento_nombre'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'documento_id' => 'Documento ID',
            'documento_nombre' => 'Documento Nombre',
            'documento_proceso_id' => 'Documento Proceso ID',
            'documento_carpeta_id' => 'Documento Carpeta ID',
        ];
    }
}

controllers/DocumentosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Documentos;
use app\models\DocumentosSearch;
use app\models\Carpetas;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\db\Query;


/**
 * DocumentosController implements the CRUD actions for Documentos model.
 */
class DocumentosController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Documentos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DocumentosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionVer()
    {

        // echo "<pre>";
        // print_r($_REQUEST);die;
        $query = new Query();
        $connection = Yii::$app->db;

        $model = new Documentos();

        $query = $connection->createCommand('SELECT * from procesos where proceso_id = ' . $_REQUEST['proceso'] . ' ');
        $tituloProceso = $query->queryAll();

        $query = $connection->createCommand('SELECT * from carpetas where carpeta_id = ' . $_REQUEST['carpeta'] . ' and carpeta_depende_id is null');
        $tituloCarpeta = $query->queryAll();

        $query = $connection->createCommand('SELECT * from carpetas where carpeta_depende_id = ' . $_REQUEST['carpeta'] . ' and carpeta_depende_id is not null ');
        $depende = $query->queryAll();

        // echo "<pre>";
        // print_r($depende);die;


        $query = $connection->createCommand('SELECT * from documentos where documento_carpeta_id = ' . $_REQUEST['carpeta'] . ' and documento_proceso_id = ' . $_REQUEST['proceso'] . ' ');
        $result = $query->queryAll();

        return $this->render('ver', [
            'archivos' => $result,
            'carpeta' => $_REQUEST['carpeta'],
            'proceso' => $_REQUEST['proceso'],
            'model' => $model,
            'tituloProceso' => $tituloProceso,
            'tituloCarpeta' => $tituloCarpeta,
            'depende' => $depende,
        ]);
    }

    public function actionVerdepende()
    {

        // echo "<pre>";
        // print_r($_REQUEST);
        // die;

        $query = new Query();
        $query1 = new Query();
        $query2 = new Query();
        $query3 = new Query();
        $query4 = new Query();
        $connection = Yii::$app->db;
        $model = new Documentos();

        $query = $connection->createCommand('SELECT *
                                                  from documentos 
                                                 where documento_carpeta_id = ' . $_REQUEST['carpeta'] . '  ');
        $documentosDepende = $query->queryAll();

        $query1 = $connection->createCommand('select * from procesos where proceso_id = ' . $_REQUEST['proceso'] . ' ');
        $procesonombre = $query1->queryAll();

        $query2 = $connection->createCommand('select * from carpetas where carpeta_id = ' . $_REQUEST['depende'] . '');
        $dependenombre = $query2->queryAll();

        $query4 = $connection->createCommand('select * from carpetas where carpeta_depende_id=' . $_REQUEST['carpeta']);
        $carpetadepende=$query4->queryAll();

        $query3 = $connection->createCommand('select * from carpetas where carpeta_id = ' . $_REQUEST['carpeta'] . '');
        $final = $query3->queryAll();

        // echo "<pre>";
        // print_r($carpetadepende);
        // print_r($dependenombre);
        // print_r($procesonombre);
        // print_r($final);
        // die();

        return $this->render('verdepende', [
            'documentos' => $documentosDepende,
            'carpetadepende'=>$carpetadepende,
            'proceso' => $procesonombre,
            'depende' => $dependenombre,
            'final' => $final,
            'model' => $model,
        ]);
    }



    public function actionVersubdepende()
    {



        $query = new Query();
        $connection = Yii::$app->db;
        $model = new Documentos();

        $query = $connection->createCommand('SELECT *
                                                  from documentos 
                                                 where documento_carpeta_id = ' . $_REQUEST['carpeta'] . '  ');
        $documentosDepende = $query->queryAll();

        $query = $connection->createCommand('select * from procesos where proceso_id = ' . $_REQUEST['proceso'] . ' ');
        $procesonombre = $query->queryAll();

        $query = $connection->createCommand('select * from carpetas where carpeta_id = ' . $_REQUEST['depende'] . '');
        $dependenombre = $query->queryAll();

        $query = $connection->createCommand('select * from carpetas where carpeta_id = ' . $_REQUEST['carpeta'] . '');
        $final = $query->queryAll();

        // echo "<pre>";
        // print_r($dependenombre);
        // print_r($procesonombre);
        // die();
        return $this->render('versubdepende', [
            'documentos' => $documentosDepende,
            'proceso' => $procesonombre,
            'depende' => $dependenombre,
            'final' => $final,
            'model' => $model,
        ]);
    }

    public function actionAuditoria()
    {
        $model = new Documentos();
        $searchModel = new DocumentosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $query = new Query();
        $connection = Yii::$app->db;

        $query = $connection->createCommand('SELECT *, 
                                                    (select count(*) from documentos where documento_carpeta_id = carpeta_id and documento_proceso_id = proceso_id) as documentos
                                            from    procesos
                                                    join carpetas on (proceso_id = carpeta_proceso_id and carpeta_depende_id is null)
                                            where   proceso_id = 1
                                            order by  carpeta_id');
        $result = $query->queryAll();

        $query = $connection->createCommand('SELECT *
                                            from    documentos
                                            where   documento_proceso_id = 1
                                                    and documento_carpeta_id is null
                                            order by 1 asc ');
        $sinCarpeta = $query->queryAll();

        // echo "<pre>";
        // print_r($result);die;

        return $this->render('indexauditoria', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'result' => $result,
            'model' => $model,
            'archivos' => $sinCarpeta,
        ]);
    }
    public function actionContabilidad()
    {
        $model = new Documentos();
        $searchModel = new DocumentosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $query = new Query();
        $connection = Yii::$app->db;

        $query = $connection->createCommand('SELECT *, 
                                                    (select count(*) from documentos where documento_carpeta_id = carpeta_id and documento_proceso_id = proceso_id) as documentos
                                            from    procesos
                                                    join carpetas on (proceso_id = carpeta_proceso_id)
                                            where   proceso_id = 2
                                            order by  carpeta_id');
        $result = $query->queryAll();

        $query = $connection->createCommand('SELECT *
                                            from    documentos
                                            where   documento_proceso_id = 2
                                                    and documento_carpeta_id is null
                                            order by 1 asc ');
        $sinCarpeta = $query->queryAll();

        return $this->render('indexcontabilidad', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'result' => $result,
            'model' => $model,
            'archivos' => $sinCarpeta,
        ]);
    }
    public function actionDireccionejecutiva()
    {
        $model = new Documentos();
        $searchModel = new DocumentosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $query = new Query();
        $connection = Yii::$app->db;

        $query = $connection->createCommand('SELECT *, 
                                                    (select count(*) from documentos where documento_carpeta_id = carpeta_id and documento_proceso_id = proceso_id) as documentos
                                            from    procesos
                                                    join carpetas on (proceso_id = carpeta_proceso_id)
                                            where   proceso_id = 3
                                            order by  carpeta_id');
        $result = $query->queryAll();
        $query = $connection->createCommand('SELECT *
                                            from    documentos
                                            where   documento_proceso_id = 3
                                                    and documento_carpeta_id is null
                                            order by 1 asc ');
        $sinCarpeta = $query->queryAll();

        return $this->render('indexdireccionejecutiva', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

views/documentos/indexauditoria.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DocumentosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Auditoria';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documentos-index">
    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <div class="card " >
        <div class="card-header alert alert-primary">Auditoria</div>
        <div class="card-body">
        <?php if(!Yii::$app->user->isGuest){ ?>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalLong">
                Cargar Documentos
            </button><br>
        <?php } ?>
            <?php if ($result!="") { ?>
                <br><ul class="list-group">
                <?php
                    $contador=1; 
                    foreach ($result as $keyC => $valueC) { ?>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <?= Html::a($contador.'- '.$valueC['carpeta_nombre'], ['documentos/ver' , 'proceso'=>'1', 'carpeta' => $valueC['carpeta_id']], ['class' => '']) ?>
                        <span class="badge badge-primary badge-pill"><?php  echo $valueC['documentos'] ?></span>
                    </li>
                <?php  $contador++; } ?>
                
                </ul>
            <?php } ?>
          
            <?php if(Yii::$app->user->isGuest){ ?>

                <?php if ($archivos!=null) { ?>
                    <br><ul class="list-group">
                    <?php
                        $contador=1; 
                        foreach ($archivos as $keyC => $valueC) { ?>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="<?php echo Url::base(); ?>/<?php echo $valueC['documento_ruta'] ?>" target="_blank" class=""><?php echo $valueC['documento_nombre'] ?></a>
                        </li>
                    <?php  $contador++; } ?>
                    
                    </ul>
                <?php } ?>

                <?php }else{ if ($archivos!=null) {?>
                <table class="table table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre Archivo</th>
                            <th scope="col">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                        $contador=1; 
                        foreach ($archivos as $keyC => $valueC) { ?>
                        <tr>
                            <td>
                            <?php echo $contador ?>
                            </td>
                            <td>
                                <a href="<?php echo Url::base(); ?>/<?php echo $valueC['documento_ruta'] ?>" target="_blank" class=""><?php echo $valueC['documento_nombre'] ?></a>
                            </td>
                            <td>
                            <center>
                                <button class="btn btn-outline-danger btnEliminar1" data-toggle="modal" id="<?php echo $valueC['documento_id'] ?>" data-target="#eliminar">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                            </center>
                            </td>
                        </tr>
                    <?php  $contador++; } ?>

                    </tbody>
                </table>


                <?php } } ?>



        </div>
    </div>
</div>





<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Carga de Documentos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <?php $form = ActiveForm::begin([
                                  'method' => 'post',
                                  'options' => ["enctype" => "multipart/form-data"],
                                  'action' => ['documentos/carga'],
                                ]); ?>
          <div class="modal-body">
              <input type="hidden" name="proceso" value="1">
              <div >
                  <?= $form->field($model, "documento_nombre[]")->fileInput(['multiple' => true])->label(false); ?>
              </div>
          </div>   
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Subir Documento</button>
      </div>
      <?php ActiveForm::end(); ?>     
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="eliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Eliminación de Documentos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            <p>Una Eliminado el archivo no se podra recuperar y debera Cargarlo nuevamente</p>
            </div>
            <div class="modal-footer">
                <input type="hidden" id="idarchivo">
                <button type="button" id="eliminarArchivo" class="btn btn-danger" >Eliminar Archivo</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>

$( document ).ready(function() {

 $('.btnEliminar1').click(function(){
     $('#idarchivo').val($(this).attr('id'));
 })

 $('#eliminarArchivo').click(function(){
    
    $.ajax({
            url: '<?php echo Yii::$app->request->baseUrl ?>/?r=documentos/eliminardocumento',
            type: 'get',
            data: {
                id : $('#idarchivo').val(), 
            },
            success: function (data) {
                location.reload();
            }
        }); // fin ajax
 });

});


</script>

views/documentos/indexcalidad.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $searchModel app\models\DocumentosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'SG SST';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documentos-index">
    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <div class="card " >
        <div class="card-header alert alert-primary">Gestión de Calidad</div>
        <div class="card-body">
        <?php if(!Yii::$app->user->isGuest){ ?>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalLong">
                Cargar Documentos
            </button><br>
        <?php } ?>
        <?php if ($result!="") { ?>
                <br><ul class="list-group">
                <?php
                    $contador=1; 
                    foreach ($result as $keyC => $valueC) { ?>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <?= Html::a($contador.'- '.$valueC['carpeta_nombre'], ['documentos/ver' , 'proceso'=>'9', 'carpeta' => $valueC['carpeta_id']], ['class' => '']) ?>
                        <span class="badge badge-primary badge-pill"><?php  echo $valueC['documentos'] ?></span>
                    </li>
                <?php  $contador++; } ?>
                
                </ul>
            <?php } ?>
          
            <?php if(Yii::$app->user->isGuest){ ?>

                <?php if ($archivos!=null) { ?>
                    <br><ul class="list-group">
                    <?php
                        $contador=1; 
                        foreach ($archivos as $keyC => $valueC) { ?>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="<?php echo Url::base(); ?>/<?php echo $valueC['documento_ruta'] ?>" target="_blank" class=""><?php echo $valueC['documento_nombre'] ?></a>
                        </li>
                    <?php  $contador++; } ?>
                    
                    </ul>
                <?php } ?>      

        <?php }else{ if ($archivos!=null) {?>
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre Archivo</th>
                        <th scope="col">Acción</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                    $contador=1; 
                    foreach ($archivos as $keyC => $valueC) { ?>
                    <tr>
                        <td>
                        <?php echo $contador ?>
                        </td>
                        <td>
                            <a href="<?php echo Url::base(); ?>/<?php echo $valueC['documento_ruta'] ?>" target="_blank" class=""><?php echo $valueC['documento_nombre'] ?></a>
                        </td>
                        <td>
                        <center>
                            <button class="btn btn-outline-danger btnEliminar1" data-toggle="modal" id="<?php echo $valueC['documento_id'] ?>" data-target="#eliminar">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </button>
                        </center>
                        </td>
                        
                    </tr>
                <?php  $contador++; } ?>

                </tbody>
            </table>


        <?php } } ?>

        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Carga de Documentos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <?php $form = ActiveForm::begin([
                                  'method' => 'post',
                                  'options' => ["enctype" => "multipart/form-data"],
                                  'action' => ['documentos/carga'],
                                ]); ?>
          <div class="modal-body">
              <input type="hidden" name="proceso" value="9">
              <div >
                  <?= $form->field($model, "documento_nombre[]")->fileInput(['multiple' => true])->label(false); ?>
              </div>
          </div>   
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Subir Documento</button>
      </div>
      <?php ActiveForm::end(); ?>     
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="eliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Eliminación de Documentos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            <p>Una Eliminado el archivo no se podra recuperar y debera Cargarlo nuevamente</p>
            </div>
            <div class="modal-footer">
                <input type="hidden" id="idarchivo">
                <button type="button" id="eliminarArchivo" class="btn btn-danger" >Eliminar Archivo</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<script>

$( document ).ready(function() {

 $('.btnEliminar1').click(function(){
     $('#idarchivo').val($(this).attr('id'));
 })

 $('#eliminarArchivo').click(function(){
    
    $.ajax({
            url: '<?php echo Yii::$app->request->baseUrl ?>/?r=documentos/eliminardocumento',
            type: 'get',
            data: {
                id : $('#idarchivo').val(), 
            },
            success: function (data) {
                location.reload();
            }
        }); // fin ajax
 });

});


</script>

views/documentos/indexcontabilidad.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $searchModel app\models\DocumentosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Contabilidad';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documentos-index">
    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <div class="card " >
        <div class="card-header alert alert-primary">Contabilidad</div>
        <div class="card-body">
        <?php if(!Yii::$app->user->isGuest){ ?>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalLong">            
                Cargar Documentos
            </button><br>
        <?php } ?>
        <?php if ($result!="") { ?>
                <br><ul class="list-group">
                <?php
                    $contador=1; 
                    foreach ($result as $keyC => $valueC) { ?>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <?= Html::a($contador.'- '.$valueC['carpeta_nombre'], ['documentos/ver' , 'proceso'=>'2', 'carpeta' => $valueC['carpeta_id']], ['class' => '']) ?>
                        <span class="badge badge-primary badge-pill"><?php  echo $valueC['documentos'] ?></span>
                    </li>
                <?php  $contador++; } ?>
                
                </ul>
            <?php } ?>
          
            <?php if(Yii::$app->user->isGuest){ ?>

                <?php if ($archivos!=null) { ?>
                    <br><ul class="list-group">
                    <?php
                        $contador=1; 
                        foreach ($archivos as $keyC => $valueC) { ?>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="<?php echo Url::base(); ?>/<?php echo $valueC['documento_ruta'] ?>" target="_blank" class=""><?php echo $valueC['documento_nombre'] ?></a>
                        </li>
                    <?php  $contador++; } ?>
                    
                    </ul>
                <?php } ?>      

        <?php }else{ if ($archivos!=null) {?>
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre Archivo</th>
                        <th scope="col">Acción</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                    $contador=1; 
                    foreach ($archivos as $keyC => $valueC) { ?>
                    <tr>
                        <td>
                        <?php echo $contador ?>
                        </td>
                        <td>
                            <a href="<?php echo Url::base(); ?>/<?php echo $valueC['documento_ruta'] ?>" target="_blank" class=""><?php echo $valueC['documento_nombre'] ?></a>
                        </td>
                        <td>
                        <center>
                            <button class="btn btn-outline-danger btnEliminar1" data-toggle="modal" id="<?php echo $valueC['documento_id'] ?>" data-target="#eliminar">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </button>
                        </center>

                        </td>
                        
                    </tr>
                <?php  $contador++; } ?>

                </tbody>
            </table>


        <?php } } ?>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Carga de Documentos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <?php $form = ActiveForm::begin([
                                  'method' => 'post',
                                  'options' => ["enctype" => "multipart/form-data"],
                                  'action' => ['documentos/carga'],
                                ]); ?>
          <div class="modal-body">
              <input type="hidden" name="proceso" value="2">
              <div >
                  <?= $form->field($model, "documento_nombre[]")->fileInput(['multiple' => true])->label(false); ?>
              </div>
          </div>   
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Subir Documento</button>
      </div>
      <?php ActiveForm::end(); ?>     
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="eliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Eliminación de Documentos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            <p>Una Eliminado el archivo no se podra recuperar y debera Cargarlo nuevamente</p>
            </div>
            <div class="modal-footer">
                <input type="hidden" id="idarchivo">
                <button type="button" id="eliminarArchivo" class="btn btn-danger" >Eliminar Archivo</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>

$( document ).ready(function() {

 $('.btnEliminar1').click(function(){
     $('#idarchivo').val($(this).attr('id'));
 })

 $('#eliminarArchivo').click(function(){
    
    $.ajax({
            url: '<?php echo Yii::$app->request->baseUrl ?>/?r=documentos/eliminardocumento',
            type: 'get',
            data: {
                id : $('#idarchivo').val(), 
            },
            success: function (data) {
                location.reload();
            }
        }); // fin ajax
 });

});


</script>